### ISSUE TITLE
Thread leak in BigTable client

### ISSUE THREAD

**Issue by yaojuncn** [GoogleCloudPlatform/cloud-bigtable-client#1470]
BigTable client: com.google.cloud.bigtable:bigtable-hbase-1.x-hadoop:1.0.0-pre1
Runtime: dataproc 1.1  (Apache Spark 2.0.2), 

Problem:
after running the spark jobs for about 8 hours, it get out of memory 

the heap dump showed that there are too many grpc threads created, i think there is a thread leak. 

there are 229 grpc threads created, each contain about 10MB, which is about 2.3GB in total.

**Comment by sduskis** [comment]
We were discussing this issue internally.  Here was my response:

We had a similar problem using Dataflow.  The problem turned out to be that we were opening too many Connections in a single VM, and each connection needed some threads from the thread pool.  We initially solved that problem by caching the HBase Connection object in a transient member variable, so that there would be only a single Connection per JVM.  We later added a more elegant solution that cached the underlying gRPC Channel objects.  I would recommend the following option settings that can be set either in an hbase-site.xml, or a hadoop Configuration object:

`"google.bigtable.use.cached.data.channel.pool" = "true"`   // This enables caching of the underlying gRPC channels
`"google.bigtable.endpoint.host" = "batch-bigtable.googleapis.com"`  // This directs operations to a set of production servers dedicated to batch jobs, which helps overall system health.

// These options help with settings meant for batch operations rather than "online" operations:
`"google.bigtable.grpc.retry.initial.elapsed.backoff.ms" = "5000"`      // Wait 5 seconds before retrying operations.  This helps reduce the likelihood of overloading the server-side 
`"google.bigtable.grpc.retry.max.elapsed.backoff.ms" = "300,000"`  // Keep on retrying for 5 minutes rather than 1 minute.

[Here]( https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-dataflow-parent/bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java#L165)'s where we set those values for Dataflow.

**Comment by yaojuncn** [comment]
@sduskis   
thanks for the quick response,  so trying to understand the case,  

1. when you say "we were opening too many Connections in a single VM, and each connection needed some threads from the thread pool",  I assume you are referring to the internal implementation in the library, right? 

2. Also I am a little bit confused by 
"We initially solved that problem by caching the HBase Connection object in a transient member variable, so that there would be only a single Connection per JVM", 
are you referring to the usage of the library or the internal implementation in the library? 

the reason I have these two questions is that when I check the heapdump and do OQL with "select * from com.google.cloud.bigtable.hbase1_x.BigtableConnection ", there is only one instance of the BigTableConnection, which is what we did in our code.  so on our side, we are already using one connection only.  
when you say the many connections, are you referring to the gRPC connection to each region server?  but do you mention about "caching the HBase Connection object"?

3. so all the 4 properties are suggested to set?  
is the one of "google.bigtable.endpoint.host" = "batch-bigtable.googleapis.com" really needed? 
will this cause any bad impact or future issues that something changed after time? 

when I say I am running on spark, we are doing the bigTable operation in the spark driver node in a very low qps,  there is some batch operations but not really too big..

so far we have existing settings as below:
            conf.set("google.bigtable.rpc.use.timeouts", "true");
            conf.set("google.bigtable.rpc.timeout.ms", "2000");
            conf.set("google.bigtable.grpc.retry.max.elapsed.backoff.ms", "2000");

**Comment by sduskis** [comment]
1 & 2: You were doing the right thing with the single instance of BigtableConnection.  You can ignore the other details.

3: For now, it doesn't make a difference.  Longer term, batch-bigtable will have some settings for heavy batch loads to reduce the chances of batch jobs interfering with other traffic against a Cloud Bigtable cluster.  If you don't have heavy batch loads, then you don't have to set this.

I'll run a few tests to see if I can get a better understanding of what's going on.

On another note I could add an option to use the directExecutor() instead of a ThreadPool based Executor to get around this problem.

**Comment by yaojuncn** [comment]
so, right now what may help on this is to set this option? 
"google.bigtable.use.cached.data.channel.pool" = "true"

**Comment by sduskis** [comment]
That option won't help you if you only have a single BigtableConnection.

**Comment by yaojuncn** [comment]
so this means  we do not have any solutions over this issue as of now?

**Comment by sduskis** [comment]
We're still looking at this.  We have some leads.  @igorbernstein2 and I spoke offline.  My suggestion about directExecutor() won't work for your case, since you use scans.  The problem might relate to how the Cloud Bigtable client handles scans with BlockingQueues.

**Comment by igorbernstein2** [comment]
Hi @yaojuncn,

We are still investigating. It would very helpful if you could provide us a bit more detail as to what your workload is?  Are you running full scans? or partial scans? point lookups? etc

Thanks!

**Comment by yaojuncn** [comment]
@igorbernstein2 
here is our bigtable operation in every minute, all this is happening in the spark driver node, so it is only executing on one node. 

at beginning:
1.  do a rowkey scan with start row and setMaxResultSize(1)
2. do a checkandput on a single rowkey
3. do a get on a single rowkey
4. do a get on a single rowkey

at the end:
1. do a batch put of about 1500 rowkeys
2. do a put on a single rowkey

**Comment by sduskis** [comment]
The rowkey scan with start row and setMaxResultSize(1) is likely tickling a bug in the client that we're looking into.  

MaxResultSize is a setting on RPC result size, not the number of rows; the HBase API is non intuitive.  If you want a single row, you should use a PageFilter.

**Comment by yaojuncn** [comment]
thanks for this. 
I will make the change my side.  
the other operations are also slow here.  and thread leak is still going on.

**Comment by sduskis** [comment]
The thread leek probably originated from the way you were doing scans as well as poor behavior of the bigtable client.  @igorbernstein2 and I had quite along conversation about this issue today.  

Hopefully between your changes and another change that I'm working on, we can get through the thread leak issue by early next week.

**Comment by yaojuncn** [comment]
that's surprised that doing such a scan will cause thread leak, in other usages we do have usages do many more scan

btw, I am actually trying to rollback to this version and am testing on it, 
com.google.cloud.bigtable:bigtable-hbase-1.2:0.9.3

do you see any big known issues on this version?

**Comment by sduskis** [comment]
0.9.2 and 0.9.3 had some major issues regarding reads.  We used a bad version of netty which had a memory leak.  We rolled back netty in the 0.9.4 release. 

The biggest problems in 0.9.4-0.9.6 related to batch puts.  There were potential silent losses of data in those versions.  I would suggest 0.9.7.1 instead; that version at least lets you know when there's a problem.

[Here](https://cloud.google.com/bigtable/docs/release-notes)'s our release notes to dig into this in more detail.

**Comment by sduskis** [comment]
The leak happens when there is data that wasn't read in the buffer.  You were constructing queries that returned a whole bunch of data, and ignored it.  Our scanner currently doesn't clean up after itself well in those situations.  That problem would have likely been there for quite a while, including the 0.9.3 release.  The client's behavior has never been correct, and I'm guessing that there was a change in gRPC that exacerbated that incorrect behavior.

**Comment by yaojuncn** [comment]
the wired thing is, we have been using 0.9.2 and 0.9.3 over a year in other projects, 
then in this spark job, we start to see long operation (50 minutes),  when adding timeout, google also suggested us to upgrade the version, then we get thread leak constantly....

**Comment by sduskis** [comment]
I think we submitted a fix for this problem with #1471, although it's hard to tell definitively without a reproduction case.  I'm in the process of releasing a 1.0.0-pre3-SNAPSHOT with that change.

**Comment by sduskis** [comment]
yaojuncn@, the thread leaks should not be present if you use the 1.0.0-pre2 and the PageFilter.  Have you tested that combination?

**Comment by yaojuncn** [comment]
@sduskis 
if you do a fix, could you also do a patch to 0.9.2, 0.9.3 and 0.9.7.1 ? 
the thing is, two of are mission critical projects are using 0.9.2 and 0.9.3 for about one year and they are running fine so far, 
so we may probably want to continue these versions if we do not have any big issues on these versions. 
and since you said 0.9.2 and 0.9.3 are also having memory issues and suggested 0.9.7.1, we may also want to evaluate 0.9.7.1. if you can make a patch that will be also worth testing. 

in terms of the netty issue you mentioned, we use this dependency based on some google doc. will this  avoid the memory issue you mentioned in 0.9.2 or 0.9.3?
'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork19'

I did not test 1.0.0-pre2 with PageFilter yet. will let you know once verified.

**Comment by sduskis** [comment]
Our policy in general, is to release new versions, and not backport; it's not practical for us to do that.  0.9.7 will not get new patches unless there's an extreme reason to do so.

In terms of netty, I meant the `io.netty:netty-handler`, `io.netty:netty-codec-http2`, `io.netty:netty-handler-proxy` that you can see [here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/bigtable-client-1.0.0-pre2/bigtable-client-core-parent/bigtable-client-core/pom.xml#L110).  They are under the control of the Cloud Bigtable client, and incorporated into the cloud bigtable client jar using the maven shade plugin.  They are not something you can control.

**Comment by sduskis** [comment]
We fixed this in 1.0.0-pre3.  I'm closing this.

**Comment by yaojuncn** [comment]
a curious question to jump in here,  is there are doc url of bug list (status) for each version?

**Comment by yaojuncn** [comment]
Also, one curious question about this leak, for the original version, we tried to call org.apache.hadoop.hbase.client.Connection.close() every time after the operation, hoping that all the resources will be closed. but it turned out that the leak is still happening, 
do you have any ideas why that doesn't help? 

thanks.

**Comment by igorbernstein2** [comment]
Hi,

The leak was caused by a grpc thread blocking on a full buffer in the bigtable. Closing the connection wouldn't unblock the thread. The fix was to improve flow control and prevent grpc from blocking on a full buffer.
